<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


    <xacro:include filename="other_parts/box_with_fillet_macro.xacro"/>
    <xacro:include filename="other_parts/drive_wheel_macro.xacro"/>
    <xacro:include filename="other_parts/drive_wheel_rim_macro.xacro"/>
    
    <xacro:include filename="sensors/sonar.xacro"/>
    <xacro:include filename="sensors/lidar.xacro"/>
    <xacro:include filename="sensors/imu.xacro"/>
    <xacro:include filename="sensors/cam.xacro"/>


    <xacro:property name="chassis_radius" value="0.13"/>
    <xacro:property name="chassis_thickness" value="0.005"/>
    <xacro:property name="chassis_mass" value="2.0"/>
    <xacro:property name="beam_height" value="0.05"/>
    <xacro:property name="beam_radius" value="0.005"/>
    <xacro:property name="chassis_color" value="orange"/>


    <xacro:property name="wheel_seperation" value="0.22"/>
    <xacro:property name="wheel_radius" value="0.034"/>
    <xacro:property name="wheel_width" value="0.026"/>
    <xacro:property name="wheel_mass" value="0.08"/>

    <xacro:property name="castor_wheel_radius" value="${wheel_radius/2}"/>
    <xacro:property name="castor_wheel_mass" value="0.04"/>

    






    <!-- BASE LINK -->

    <!-- <base joint/> -->
    <link name="base_link">  
    </link>

    <!-- ################# -->





    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0 0 ${wheel_radius}"/>
    </joint>



    <link name="chassis">

      <visual>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <cylinder radius="${chassis_radius}" length="${chassis_thickness}"/>
          </geometry>
          <material name="${chassis_color}"/>
      </visual>
      <visual>
          <origin xyz="0 0 ${beam_height}" rpy="0 0 0"/>
          <geometry>
            <cylinder radius="${chassis_radius}" length="${chassis_thickness}"/>
          </geometry>
          <material name="${chassis_color}"/>
      </visual>
      <visual>
          <origin xyz="0 0 ${beam_height*2}" rpy="0 0 0"/>
          <geometry>
            <cylinder radius="${chassis_radius}" length="${chassis_thickness}"/>
          </geometry>
          <material name="${chassis_color}"/>
      </visual>


      <visual>
          <origin xyz="${chassis_radius/2} ${chassis_radius/2} ${beam_height}" rpy="0 0 0"/>
          <geometry>
            <cylinder radius="${beam_radius}" length="${beam_height*2}"/>
          </geometry>
          <material name="${chassis_color}"/>
      </visual>
      <visual>
          <origin xyz="${chassis_radius/2} ${-chassis_radius/2} ${beam_height}" rpy="0 0 0"/>
          <geometry>
            <cylinder radius="${beam_radius}" length="${beam_height*2}"/>
          </geometry>
          <material name="${chassis_color}"/>
      </visual>
      <visual>
          <origin xyz="${-chassis_radius/2} ${chassis_radius/2} ${beam_height}" rpy="0 0 0"/>
          <geometry>
            <cylinder radius="${beam_radius}" length="${beam_height*2}"/>
          </geometry>
          <material name="${chassis_color}"/>
      </visual>
      <visual>
          <origin xyz="${-chassis_radius/2} ${-chassis_radius/2} ${beam_height}" rpy="0 0 0"/>
          <geometry>
            <cylinder radius="${beam_radius}" length="${beam_height*2}"/>
          </geometry>
          <material name="${chassis_color}"/>
      </visual>


      <collision>
          <origin xyz="0 0 ${beam_height}" rpy="0 0 0"/>
          <geometry>
            <cylinder radius="${chassis_radius}" length="${beam_height*2}"/>
          </geometry>
      </collision>
      <xacro:inertial_cylinder mass="${chassis_mass}" length="${chassis_thickness}" radius="${chassis_radius}">
          <origin xyz="${-chassis_radius/1.5} 0 0" rpy="0 0 0"/>
      </xacro:inertial_cylinder>
    </link>
    <gazebo reference="chassis">
        <!-- <material>Gazebo/DarkGrey</material> -->
        <material>Gazebo/Orange</material>
    </gazebo>

    <!--  ########################### -->










    <!-- LEFT DRIVE WHEEL -->

    <xacro:insert_drive_wheel 
        base_name="left_wheel" 
        parent_name="base_link" 
        x="0" y="${wheel_seperation/2}" z="${wheel_radius}"
        mass="${wheel_mass}"
        radius="${wheel_radius}"
        thickness="${wheel_width}"/>
  
    <xacro:insert_drive_wheel_rim
        base_name="left_rim" 
        parent_name="left_wheel" 
        x="0" y="0" z="0.001"
        radius="${wheel_radius}"
        thickness="${wheel_width}"
        spoke_width="0.005"/>

    <!-- ############################# -->








    <!-- RIGHT DRIVE WHEEL -->

    <xacro:insert_drive_wheel 
        base_name="right_wheel" 
        parent_name="base_link" 
        x="0" y="${-wheel_seperation/2}" z="${wheel_radius}"
        mass="${wheel_mass}"
        radius="${wheel_radius}"
        thickness="${wheel_width}"/>

    <xacro:insert_drive_wheel_rim
        base_name="right_rim" 
        parent_name="right_wheel" 
        x="0" y="0" z="-0.001"
        radius="${wheel_radius}"
        thickness="${wheel_width}"
        spoke_width="0.005"/>

    <!-- ############################# -->









    <!--  castor WHEEL LINK -->

    <joint name="castor_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="castor_wheel"/>
        <origin xyz="${-chassis_radius/1.5} 0 ${castor_wheel_radius}"/>
    </joint>


    <link name="castor_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${castor_wheel_radius}" />
            </geometry>
            <material name="silver"/>
        </visual>
        <collision>
           <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${castor_wheel_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${castor_wheel_mass}" radius="${castor_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="castor_wheel">
        <mu1>0.001</mu1>
        <mu2>0.001</mu2>
        <!-- <kp>1000000.0</kp> -->
        <!-- <kd>1.0</kd> -->
        <!-- <fdir1>1 0 0</fdir1> -->
        <!-- <minDepth>0.01</minDepth> -->
        <material>Gazebo/Silver</material>
    </gazebo>

    <!--  ########################### -->









    <!--  front-sonar -->
    <xacro:insert_sonar
        base_name="sonar_front" 
        parent_name="chassis" 
        x="${chassis_radius}" y="0" z="${beam_height+0.01}"
        rx="0" ry="0" rz="0"
        mass="0.005"
        min_range="0.02" max_range="3.0"
        resolution="0.01" visualize="false"/>
    <!--  left-sonar -->
    <xacro:insert_sonar
        base_name="sonar_left" 
        parent_name="chassis" 
        x="${chassis_radius*0.7071}" y="${chassis_radius*0.7071}" z="${beam_height+0.01}"
        rx="0.0" ry="0.0" rz="${pi/4}"
        mass="0.005"
        min_range="0.02" max_range="3.0"
        resolution="0.01" visualize="false"/>
    <!--  right-sonar -->
    <xacro:insert_sonar
        base_name="sonar_right" 
        parent_name="chassis" 
        x="${chassis_radius*0.7071}" y="${-chassis_radius*0.7071}" z="${beam_height+0.01}"
        rx="0.0" ry="0.0" rz="${-pi/4}"
        mass="0.005"
        min_range="0.02" max_range="3.0"
        resolution="0.01" visualize="false"/>

    
     <!--  lidar -->
    <xacro:property name="lidar_z_offset" value="0.04"/>
    <xacro:insert_lidar 
        base_name="lidar" 
        parent_name="chassis" 
        x="0" y="0" z="${(beam_height*2)+lidar_z_offset}"
        mass="0.1" samples="360"
        min_angle="${-pi*2}" max_angle="${pi*2}"
        min_range="0.1" max_range="10"
        visualize="false"/>

    

    <!--  imu -->
    <xacro:insert_imu
        base_name="imu" 
        parent_name="chassis" 
        x="0" y="0" z="${beam_height}"/>



    <!-- camera -->
    <xacro:property name="cam_x_offset" value="0.04"/>
    <xacro:property name="cam_z_offset" value="0.02"/>
    <xacro:insert_camera
        base_name="camera" 
        parent_name="chassis" 
        x="${(chassis_radius)+cam_x_offset}" y="0" z="${(beam_height*2)}"
        mass="0.005"
        width="320" height="240"
        min_range="0.02" max_range="5.0"
        tilt_angle="0"
        visualize="false"/>



</robot>